name: Build and Deploy

on:
  workflow_call:
    inputs:
      env_input:
        type: string
        required: true

jobs:
  Deploy:
    runs-on: ubuntu-latest
    name: Build and Deploy to Cloud Run
    environment: ${{ inputs.env_input }}

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Cache Docker layers
        uses: actions/cache@v3
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-buildx-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-buildx-

      - name: Login to GAR
        uses: docker/login-action@v2
        with:
          registry: '${{ secrets.GCP_REGION }}-docker.pkg.dev'
          username: _json_key
          password: ${{ secrets.GCP_SA_KEY }}

      - name: Assign secrets to .env
        shell: bash
        run: |
          echo "${{ secrets.NEXT_JS_ENV }}" > .env

      - name: Build and push
        uses: docker/build-push-action@v3
        with:
          context: .
          push: true
          tags: '${{ secrets.GCP_REGION }}-docker.pkg.dev/${{ secrets.RUN_IMAGE_TAG }}:latest'
          cache-from: type=local,src=/tmp/.buildx-cache
          cache-to: type=local,dest=/tmp/.buildx-cache-new,mode=max

      - name: Move cache
        run: |
          rm -rf /tmp/.buildx-cache
          mv /tmp/.buildx-cache-new /tmp/.buildx-cache
      - name: GCP auth
        uses: google-github-actions/auth@v0
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }}

      - name: Deploy Cloud Run
        uses: google-github-actions/deploy-cloudrun@v0
        with:
          service: ${{ secrets.RUN_SERVICE_NAME }}
          image: '${{ secrets.GCP_REGION }}-docker.pkg.dev/${{ secrets.RUN_IMAGE_TAG }}'
          region: ${{ secrets.GCP_REGION }}
