name: Entry

on:
  push:
    branches:
      - main
      - dev

jobs:
  apply-env:
    name: Apply env
    runs-on: ubuntu-latest
    outputs:
      env_var: ${{ steps.var.outputs.env_var }}
    steps:
      - id: var
        run: echo "env_var=$GITHUB_REF_NAME" >> $GITHUB_OUTPUT
  call-workflow:
    needs:
      - apply-env
    name: Call workflow
    secrets: inherit
    uses: ./.github/workflows/build-and-deploy.yml
    with:
      env_input: ${{ needs.apply-env.outputs.env_var }}
